name: fipe_flutter
description: Pacote para uso da api FIPE, retornando informações de carros na tabela FIPE.
version: 0.0.1
homepage: https://leonardobenedeti.github.io/fipe_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: 1.22.6

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
